emoticons = {
    u":‑)": "Happy_face_or_smiley",
    u":-))": "Very_Happy_face_or_smiley",
    u":-)))": "Very_very_Happy_face_or_smiley",
    u":)": "Happy_face_or_smiley",
    u":))": "Very_Happy_face_or_smiley",
    u":)))": "Very_very_Happy_face_or_smiley",
    u":-]": "Happy_face_or_smiley",
    u":]": "Happy_face_or_smiley",
    u":-3": "Happy_face_smiley",
    u":3": "Happy_face_smiley",
    u":->": "Happy_face_smiley",
    u":>": "Happy_face_smiley",
    u"8-)": "Happy_face_smiley",
    u":o)": "Happy_face_smiley",
    u":-}": "Happy_face_smiley",
    u":}": "Happy_face_smiley",
    u":-)": "Happy_face_smiley",
    u":c)": "Happy_face_smiley",
    u":^)": "Happy_face_smiley",
    u"=]": "Happy_face_smiley",
    u"=)": "Happy_face_smiley",
    u":‑D": "Laughing, big_grin_or_laugh_with_glasses",
    u":D": "Laughing, big_grin_or_laugh_with_glasses",
    u"8‑D": "Laughing, big_grin_or_laugh_with_glasses",
    u"8D": "Laughing, big_grin_or_laugh_with_glasses",
    u"X‑D": "Laughing, big_grin_or_laugh_with_glasses",
    u"XD": "Laughing, big_grin_or_laugh_with_glasses",
    u"=D": "Laughing, big_grin_or_laugh_with_glasses",
    u"=3": "Laughing, big_grin_or_laugh_with_glasses",
    u"B^D": "Laughing, big_grin_or_laugh_with_glasses",
    u":-))": "Very_happy",
    u":-(": "Frown, sad, angry_or_pouting",
    u":‑(": "Frown, sad, angry_or_pouting",
    u":(": "Frown, sad, angry_or_pouting",
    u":‑c": "Frown, sad, angry_or_pouting",
    u":c": "Frown, sad, angry_or_pouting",
    u":‑<": "Frown, sad, angry_or_pouting",
    u":<": "Frown, sad, angry_or_pouting",
    u":‑[": "Frown, sad, angry_or_pouting",
    u":[": "Frown, sad, angry_or_pouting",
    u":-||": "Frown, sad, angry_or_pouting",
    u">:[": "Frown, sad, angry_or_pouting",
    u":{": "Frown, sad, angry_or_pouting",
    u":@": "Frown, sad, angry_or_pouting",
    u">:(": "Frown, sad, angry_or_pouting",
    u":'‑(": "Crying",
    u":'(": "Crying",
    u":'‑)": "Tears_of_happiness",
    u":')": "Tears_of_happiness",
    u"D‑':": "Horror",
    u"D:<": "Disgust",
    u"D:": "Sadness",
    u"D8": "Great_dismay",
    u"D;": "Great_dismay",
    u"D=": "Great_dismay",
    u"DX": "Great_dismay",
    u":‑O": "Surprise",
    u":O": "Surprise",
    u":‑o": "Surprise",
    u":o": "Surprise",
    u":-0": "Shock",
    u"8‑0": "Yawn",
    u">:O": "Yawn",
    u":-*": "Kiss",
    u":*": "Kiss",
    u":X": "Kiss",
    u";‑)": "Wink_or_smirk",
    u";)": "Wink_or_smirk",
    u"*-)": "Wink_or_smirk",
    u"*)": "Wink_or_smirk",
    u";‑]": "Wink_or_smirk",
    u";]": "Wink_or_smirk",
    u";^)": "Wink_or_smirk",
    u":‑,": "Wink_or_smirk",
    u";D": "Wink_or_smirk",
    u":‑P": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u":P": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u"X‑P": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u"XP": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u":‑Þ": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u":Þ": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u":b": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u"d:": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u"=p": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u">:P": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u":‑/": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u":/": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u":-[.]": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u">:[(\)]": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u">:/": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u":[(\)]": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u"=/": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u"=[(\)]": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u":L": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u"=L": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u":S": "Skeptical, annoyed, undecided, uneasy_or_hesitant",
    u":‑|": "Straight_face",
    u":|": "Straight_face",
    u":$": "Embarrassed_or_blushing",
    u":‑x": "Sealed_lips_or_wearing_braces_or_tongue-tied",
    u":x": "Sealed_lips_or_wearing_braces_or_tongue-tied",
    u":‑#": "Sealed_lips_or_wearing_braces_or_tongue-tied",
    u":#": "Sealed_lips_or_wearing_braces_or_tongue-tied",
    u":‑&": "Sealed_lips_or_wearing_braces_or_tongue-tied",
    u":&": "Sealed_lips_or_wearing_braces_or_tongue-tied",
    u"O:‑)": "Angel, saint_or_innocent",
    u"O:)": "Angel, saint_or_innocent",
    u"0:‑3": "Angel, saint_or_innocent",
    u"0:3": "Angel, saint_or_innocent",
    u"0:‑)": "Angel, saint_or_innocent",
    u"0:)": "Angel, saint_or_innocent",
    u":‑b": "Tongue_sticking_out, cheeky, playful_or_blowing_a_raspberry",
    u"0;^)": "Angel, saint_or_innocent",
    u">:‑)": "Evil_or_devilish",
    u">:)": "Evil_or_devilish",
    u"}:‑)": "Evil_or_devilish",
    u"}:)": "Evil_or_devilish",
    u"3:‑)": "Evil_or_devilish",
    u"3:)": "Evil_or_devilish",
    u">;)": "Evil_or_devilish",
    u"|;‑)": "Cool",
    u"|‑O": "Bored",
    u":‑J": "Tongue-in-cheek",
    u"#‑)": "Party_all_night",
    u"%‑)": "Drunk_or_confused",
    u"%)": "Drunk_or_confused",
    u":-###..": "Being_sick",
    u":###..": "Being_sick",
    u"<:‑|": "Dump",
    u"(>_<)": "Troubled",
    u"(>_<)>": "Troubled",
    u"(';')": "Baby",
    u"(^^>``": "Nervous_or_Embarrassed_or_Troubled_or_Shy_or_Sweat_drop",
    u"(^_^;)": "Nervous_or_Embarrassed_or_Troubled_or_Shy_or_Sweat_drop",
    u"(-_-;)": "Nervous_or_Embarrassed_or_Troubled_or_Shy_or_Sweat_drop",
    u"(~_~;) (・.・;)": "Nervous_or_Embarrassed_or_Troubled_or_Shy_or_Sweat_drop",
    u"(-_-)zzz": "Sleeping",
    u"(^_-)": "Wink",
    u"((+_+))": "Confused",
    u"(+o+)": "Confused",
    u"(o|o)": "Ultraman",
    u"^_^": "Joyful",
    u"(^_^)/": "Joyful",
    u"(^O^)／": "Joyful",
    u"(^o^)／": "Joyful",
    u"(__)": "Kowtow_as_a_sign_of_respect, or_dogeza_for_apology",
    u"_(._.)_": "Kowtow_as_a_sign_of_respect, or_dogeza_for_apology",
    u"<(_ _)>": "Kowtow_as_a_sign_of_respect, or_dogeza_for_apology",
    u"<m(__)m>": "Kowtow_as_a_sign_of_respect, or_dogeza_for_apology",
    u"m(__)m": "Kowtow_as_a_sign_of_respect, or_dogeza_for_apology",
    u"m(_ _)m": "Kowtow_as_a_sign_of_respect, or_dogeza_for_apology",
    u"('_')": "Sad_or_Crying",
    u"(/_;)": "Sad_or_Crying",
    u"(T_T) (;_;)": "Sad_or_Crying",
    u"(;_;": "Sad_of_Crying",
    u"(;_:)": "Sad_or_Crying",
    u"(;O;)": "Sad_or_Crying",
    u"(:_;)": "Sad_or_Crying",
    u"(ToT)": "Sad_or_Crying",
    u";_;": "Sad_or_Crying",
    u";-;": "Sad_or_Crying",
    u";n;": "Sad_or_Crying",
    u";;": "Sad_or_Crying",
    u"Q.Q": "Sad_or_Crying",
    u"T.T": "Sad_or_Crying",
    u"QQ": "Sad_or_Crying",
    u"Q_Q": "Sad_or_Crying",
    u"(-.-)": "Shame",
    u"(-_-)": "Shame",
    u"(一一)": "Shame",
    u"(；一_一)": "Shame",
    u"(=_=)": "Tired",
    u"(=^·^=)": "cat",
    u"(=^··^=)": "cat",
    u"=_^= ": "cat",
    u"(..)": "Looking_down",
    u"(._.)": "Looking_down",
    u"^m^": "Giggling_with_hand_covering_mouth",
    u"(・・?": "Confusion",
    u"(?_?)": "Confusion",
    u">^_^<": "Normal_Laugh",
    u"<^!^>": "Normal_Laugh",
    u"^/^": "Normal_Laugh",
    u"（*^_^*）": "Normal_Laugh",
    u"(^<^) (^.^)": "Normal_Laugh",
    u"(^^)": "Normal_Laugh",
    u"(^.^)": "Normal_Laugh",
    u"(^_^.)": "Normal_Laugh",
    u"(^_^)": "Normal_Laugh",
    u"(^^)": "Normal_Laugh",
    u"(^J^)": "Normal_Laugh",
    u"(*^.^*)": "Normal_Laugh",
    u"(^—^）": "Normal_Laugh",
    u"(#^.^#)": "Normal_Laugh",
    u"（^—^）": "Waving",
    u"(;_;)/~~~": "Waving",
    u"(^.^)/~~~": "Waving",
    u"(-_-)/~~~ ($··)/~~~": "Waving",
    u"(T_T)/~~~": "Waving",
    u"(ToT)/~~~": "Waving",
    u"(*^0^*)": "Excited",
    u"(*_*)": "Amazed",
    u"(*_*;": "Amazed",
    u"(+_+) (@_@)": "Amazed",
    u"(*^^)v": "Laughing,Cheerful",
    u"(^_^)v": "Laughing,Cheerful",
    u"((d[-_-]b))": "Headphones,Listening_to_music",
    u'(-"-)': "Worried",
    u"(ーー;)": "Worried",
    u"(^0_0^)": "Eyeglasses",
    u"(＾ｖ＾)": "Happy",
    u"(＾ｕ＾)": "Happy",
    u"(^)o(^)": "Happy",
    u"(^O^)": "Happy",
    u"(^o^)": "Happy",
    u")^o^(": "Happy",
    u":O o_O": "Surprised",
    u"o_0": "Surprised",
    u"o.O": "Surprised",
    u"(o.o)": "Surprised",
    u"oO": "Surprised",
    u"(*￣m￣)": "Dissatisfied",
    u"(‘A`)": "Snubbed_or_Deflated"

}
